"""Stable Bureau public API.

The v0.1 implementation is retained in :mod:`bureau.legacy` for migration and
contract compatibility. New callers receive the revision-safe v0.2 types.
"""

from __future__ import annotations

from .legacy import (
    ACTIVE_STATES,
    BureauError,
    Claim,
    ConflictError,
    Initiative,
    NoEligibleTask,
    Reservation,
    Resource,
    StateError,
    Task,
    ValidationError,
    ancestors,
    atomic_write,
    canonical_json,
    claim_conflicts,
    default_state_dir,
    modes_conflict,
    overlaps,
    parse_time,
    read_json,
    sha256_json,
    utc_now,
)
from .v2 import (
    Dispatcher,
    Registry,
    StateStore,
    cleanup_workspace,
    close_ready_initiatives,
    complete_run,
    create_workspace,
    fail_run,
    grabowski_handoff,
    lifecycle_diagnostics,
    plan_sha256,
    preserve_workspace,
    task_revision_sha256,
    verification_stamp,
    workspace_status,
)

__all__ = [
    "ACTIVE_STATES",
    "BureauError",
    "Claim",
    "ConflictError",
    "Dispatcher",
    "Initiative",
    "NoEligibleTask",
    "Registry",
    "Reservation",
    "Resource",
    "StateError",
    "StateStore",
    "Task",
    "ValidationError",
    "ancestors",
    "atomic_write",
    "canonical_json",
    "claim_conflicts",
    "cleanup_workspace",
    "close_ready_initiatives",
    "complete_run",
    "create_workspace",
    "default_state_dir",
    "fail_run",
    "grabowski_handoff",
    "lifecycle_diagnostics",
    "modes_conflict",
    "overlaps",
    "parse_time",
    "plan_sha256",
    "preserve_workspace",
    "read_json",
    "sha256_json",
    "task_revision_sha256",
    "utc_now",
    "verification_stamp",
    "workspace_status",
]
