#!/bin/sh
set -eu
exec "$HOME/.local/bin/bureau" task-supply-run \
  --capability bureau \
  --capability grabowski \
  --capability python \
  --capability repository \
  --capability testing \
  --mutation-authority \
  --publish \
  "$@"
